import {
  BarChart3,
  BookOpen,
  CalendarCheck,
  CalendarClock,
  CheckCheck,
  ClipboardList,
  Code2,
  Copy,
  Database,
  Download,
  Eye,
  FileSpreadsheet,
  FileText,
  GraduationCap,
  KeyRound,
  Keyboard,
  Layers,
  LayoutDashboard,
  Library,
  Maximize,
  MonitorX,
  PenLine,
  Play,
  Printer,
  RotateCcw,
  Save,
  ScanSearch,
  Sheet,
  ShieldCheck,
  Shuffle,
  Sigma,
  Smartphone,
  Stamp,
  Timer,
  TrendingUp,
  UserPlus,
  Users,
  type LucideIcon,
} from "lucide-react";

export type Audience = "Teachers" | "Students" | "Admins";

export type Feature = { icon: LucideIcon; title: string; text: string; who: Audience[] };

// `photo` is an Unsplash photo id, shown in the category's banner.
export type Category = { id: string; icon: LucideIcon; photo: string; title: string; text: string; tone: string; features: Feature[] };

// Everything here works today (see the README's Features section); keep the two in step.
export const categories: Category[] = [
  {
    id: "build",
    photo: "1488190211105-8b0e65b80b4e",
    icon: ClipboardList,
    title: "Build quizzes and exams",
    text: "Write once, reuse every term, and let the subject decide which question types make sense.",
    tone: "#c0c1ff",
    features: [
      { icon: BookOpen, title: "Subject presets", text: "General, English, Mathematics, Science and Programming / IT each offer the question types that fit. “Show all question types” lifts the limit.", who: ["Teachers"] },
      { icon: Library, title: "Question bank", text: "Pick questions you've written before instead of typing them again.", who: ["Teachers"] },
      { icon: FileSpreadsheet, title: "Excel import", text: "Bring a whole set of questions in from a spreadsheet.", who: ["Teachers"] },
      { icon: Sigma, title: "Math with LaTeX", text: "Write fractions, exponents and formulas the way math teachers already do.", who: ["Teachers"] },
    ],
  },
  {
    id: "give",
    photo: "1434030216411-0b793f4b4173",
    icon: Printer,
    title: "Give them online or on paper",
    text: "The same exam runs on screen with a timer, or prints as a ready-to-copy test paper.",
    tone: "#7cc4ff",
    features: [
      { icon: CalendarClock, title: "Schedule and time limit", text: "Choose when it opens and closes and how long students get.", who: ["Teachers"] },
      { icon: Shuffle, title: "Shuffling", text: "Questions and choices in a different order for each student.", who: ["Teachers"] },
      { icon: RotateCcw, title: "Retakes", text: "None, 1, 2, 3 or unlimited; the Try again button follows the setting.", who: ["Teachers", "Students"] },
      { icon: Eye, title: "Results release", text: "Decide when students see their score and the answer key.", who: ["Teachers", "Students"] },
      { icon: Printer, title: "Test paper layout", text: "School header, paper size, part titles, footer and a live print preview.", who: ["Teachers"] },
      { icon: FileText, title: "Separate answer sheet", text: "Print an answer sheet apart from the questions when you need one.", who: ["Teachers"] },
    ],
  },
  {
    id: "integrity",
    photo: "1516321318423-f06f85e504b3",
    icon: ShieldCheck,
    title: "Anti-cheating that stays fair",
    text: "No webcam, no microphone, nothing installed. Examora logs what happens on the exam page and leaves the judgment to the teacher.",
    tone: "#d0bcff",
    features: [
      { icon: Maximize, title: "Full screen, with chances", text: "Leaving full screen is a warning; the exam submits itself after the last chance.", who: ["Teachers", "Students"] },
      { icon: Layers, title: "Tab and app switches", text: "Switching tabs, Alt+Tab and leaving the window are logged with the time.", who: ["Teachers"] },
      { icon: MonitorX, title: "One screen only", text: "In Chrome and Edge, a second monitor has to be disconnected before the exam starts.", who: ["Teachers", "Students"] },
      { icon: Copy, title: "No copy and paste", text: "Copy, paste, drag, right-click and printing are blocked; the clipboard is cleared at the start.", who: ["Teachers", "Students"] },
      { icon: Stamp, title: "Name watermark", text: "Each student's name runs faintly across their exam, so screenshots trace back.", who: ["Teachers"] },
      { icon: Timer, title: "Server-side timer", text: "Time is kept on the server, so changing the computer's clock doesn't help.", who: ["Teachers", "Students"] },
      { icon: Keyboard, title: "Typing replay", text: "Watch how a code answer was written; pasted blocks and robot-fast typing are flagged.", who: ["Teachers"] },
      { icon: ScanSearch, title: "Similarity check", text: "Code answers are compared ignoring names and comments; common solutions are ignored.", who: ["Teachers"] },
    ],
  },
  {
    id: "grading",
    photo: "1456513080510-7bf3a84b82f8",
    icon: CheckCheck,
    title: "Grading",
    text: "Everything but essays scores itself. You review what needs a person.",
    tone: "#4edea3",
    features: [
      { icon: CheckCheck, title: "Automatic scoring", text: "Multiple choice, true/false, identification, enumeration, fill in the blanks and numeric answers check against your key.", who: ["Teachers"] },
      { icon: PenLine, title: "Essays and near-misses", text: "Grade essays with comments, and accept a misspelled-but-right typed answer in one click.", who: ["Teachers"] },
      { icon: Code2, title: "Code questions", text: "Python, Java, C, C++, JavaScript and PHP (with Laravel's database layer) run against visible and hidden tests in a sandbox.", who: ["Teachers", "Students"] },
      { icon: Database, title: "SQL questions", text: "Students query your tables; their rows are compared with your answer query, with an optional hidden-data check.", who: ["Teachers", "Students"] },
    ],
  },
  {
    id: "record",
    photo: "1554224155-6726b3ff858f",
    icon: Sheet,
    title: "Class record and attendance",
    text: "Laid out like your school's Excel class record, and filled in for you.",
    tone: "#4edea3",
    features: [
      { icon: Sheet, title: "Class record that fills itself in", text: "Weights, highest possible scores, RS, the transmutation table and P, F, FA and DR remarks. Published quizzes and exams link themselves.", who: ["Teachers"] },
      { icon: Smartphone, title: "Roll call on your phone", text: "Meetings come from the class schedule: present, late, absent or excused.", who: ["Teachers"] },
      { icon: CalendarCheck, title: "Attendance rules", text: "7 lates count as 1 absence and 4 absences flag a drop, which the teacher confirms.", who: ["Teachers", "Students"] },
      { icon: Download, title: "Excel downloads", text: "The class record, and attendance per month with weekday names plus a semester summary.", who: ["Teachers"] },
    ],
  },
  {
    id: "reports",
    photo: "1551288049-bebda4e38f71",
    icon: BarChart3,
    title: "Reports",
    text: "The paperwork at the end of the term, ready to print.",
    tone: "#ffb68a",
    features: [
      { icon: GraduationCap, title: "Collegiate grade sheet", text: "Printable, straight from the class record.", who: ["Teachers"] },
      { icon: BarChart3, title: "Summary report", text: "The summary report on class academic performance, per teacher.", who: ["Teachers"] },
    ],
  },
  {
    id: "students",
    photo: "1523240795612-9a054b0db644",
    icon: GraduationCap,
    title: "For students",
    text: "What's open, what's next, and where they stand.",
    tone: "#7cc4ff",
    features: [
      { icon: LayoutDashboard, title: "Dashboard", text: "What's open, upcoming and done, plus a schedule, scores and classes.", who: ["Students"] },
      { icon: TrendingUp, title: "Standing per subject", text: "The grade so far, computed like the class record, with absences used out of the limit.", who: ["Students"] },
      { icon: Save, title: "Answers that don't get lost", text: "Saved on the device as they go, so reloading the page loses nothing.", who: ["Students"] },
      { icon: Play, title: "Run code before submitting", text: "Python and JavaScript in the browser, other languages on the server, on the sample tests only.", who: ["Students"] },
    ],
  },
  {
    id: "accounts",
    photo: "1517245386807-bb43f82c33c4",
    icon: Users,
    title: "Accounts",
    text: "Sign up with Google or any email and start right away.",
    tone: "#c0c1ff",
    features: [
      { icon: UserPlus, title: "Self sign-up", text: "Teachers and students sign up with Google or any email and start right away.", who: ["Students", "Teachers"] },
      { icon: KeyRound, title: "Google sign-in", text: "Continue with Google for the account with the same email.", who: ["Students", "Teachers", "Admins"] },
      { icon: Users, title: "Account management", text: "Admins create, edit, suspend and remove accounts and reset passwords.", who: ["Admins"] },
    ],
  },
];

// The nine question types, with a one-line example each.
export const questionTypes: { name: string; example: string; subjects: string }[] = [
  { name: "Multiple choice", example: "Which organelle makes most of a cell's ATP?", subjects: "Every subject" },
  { name: "Identification", example: "The process plants use to make food: ____", subjects: "Every subject" },
  { name: "Enumeration", example: "Give the three branches of government.", subjects: "Every subject" },
  { name: "Fill in the blanks", example: "Neither the students nor the teacher ___ late.", subjects: "English" },
  { name: "True or false", example: "A sonnet has fourteen lines.", subjects: "English" },
  { name: "Essay", example: "Explain the theme of the story in 150 words.", subjects: "English" },
  { name: "Numeric", example: "Solve for x > 0: 2x² − 18 = 0", subjects: "Mathematics" },
  { name: "Code", example: "Print the sum of the even numbers.", subjects: "Programming / IT" },
  { name: "SQL query", example: "List students with more than 3 absences.", subjects: "Programming / IT" },
];
